### ISSUE TITLE
Request for info - nesting draggables

### ISSUE THREAD

**Issue by jstortz** [SortableJS/vue.draggable.next#10]
I am curious about nesting draggables and some terminology and how it works.

Consider this pseudo code:

```html
<draggable...>
   <template #item="{ element, index }">
   </template>
</draggable>
```

What is the technical name for the "#item" attribute? Is that a slot property? A template? I've not seen that syntax before and would like to learn more.

Now consider this:

```html
<draggable...>
   <template #item="{ element, index }">
      <draggable...>
         <template #item="{ element, index }">
         </template>
      </draggable>
   </template>
</draggable>
```

This works...in so far as I can create draggable stuff within other draggable stuff. I don't seem to be able to successfully change the names of "element" and "index" though, nor sure why.

I'd really LIKE to refer to the outer element from within the inner element and cannot figure out how to do so. If I could name them differently maybe it would work, something like this:

```html
<draggable...>
   <template #item="{ outerElement, outerIndex }">
      <draggable...>
         <template #item="{ innerElement, innerIndex }">
         </template>
      </draggable>
   </template>
</draggable>
```

Any knowledge anyone can drop on me would be fantastic.

**Comment by jstortz** [comment]
Well for some reason I didn't recognize destructuring when it was right in front of my face.

So this works for anyone else wanting to do something similar:

```html
<draggable...>
   <template #item="{ element: outerElement, index: outerIndex }">
      <draggable...>
         <template #item="{ element: innerElement, index: innerIndex }">
         </template>
      </draggable>
   </template>
</draggable>
```

**Comment by ed-iv** [comment]
Cool, thanks for the tip @jstortz. Was confused about that myself.  I'm having another issue with nested draggables that I think must be common and I wonder if you've encountered it. I need to create a nested list where child elements can be moved between parents. 

So to take a todo list for example, the parent might be a 'Task' that is comprised of multiple 'Todo' children. I need to be able to move a 'Todo' from one 'Task' to another.

The issue I've run into is that after moving the children to another parent moving the (now empty) causes duplicates of its children to suddenly re-appear. Trying to resolve this using shared state (vuex) but I'm at the point now where I've got to manually adjust the underlying data structure when a drag event ends.

**Comment by sluedecke** [comment]
@jstortz Thank you, I didn't see it either.  Now I have a warning free project again :)
