### ISSUE TITLE
Feature: Long press on mobile to move

### ISSUE THREAD

**Issue by Gezellligheid** [SortableJS/vue.draggable.next#104]
I saw that the list is directly changeable on mobile.
This makes scrolling on mobile a bit anoying.

therefor maybe a `:holdToMove="true"` should be cool. This gives a small delay (2 - 3 seconds) before the user can start manipulating the list.

**Comment by samuveth** [comment]
Bump

**Comment by letstwistagain** [comment]
Bump. Any chance this will be implemented?

**Comment by vincent-lahaye** [comment]
Bump

**Comment by shushiro** [comment]
Bump, I could use this aswell

**Comment by spixy** [comment]
bump, but I think `:holdDelay="1000"` would be better (with `undefined` as default value for no delay)

**Comment by spixy** [comment]
wait, `:delay=100` already works for me (I guess its same than in https://github.com/SortableJS/Sortable#options)

**Comment by Gezellligheid** [comment]
@spixy it is included in the options yeah. But is it the same? It says `// time in milliseconds to define when the sorting should start`

**Comment by Gezellligheid** [comment]
@spixy I see that there is an `delayOnTouchOnly` so maybe the combination of those two would be the sollution

**Comment by letstwistagain** [comment]
Wow, how we all didn't find it before. Thanks @spixy! Works great for me, also in combination with touchStartThreshold.

**Comment by dliebner** [comment]
`delay` + `delayOnTouchOnly` is kind of buggy for me. A lot of the time it doesn't work, and it doesn't seem to prevent the mobile contextmenu event. If I prevent it myself, it's still kind of buggy and doesn't work half the time.
