### ISSUE TITLE
Cannot read properties of undefined (reading 'element')

### ISSUE THREAD

**Issue by rendomnet** [SortableJS/vue.draggable.next#105]
migrating from vue2 to vue3

Upgraded draggable to 4.1.0

```
  <draggable v-model="items" item-key="name">
    <template #item="{element}">
      {{ element }}
    </template>
  </draggable>
```
items is array 

`TypeError: Cannot read properties of undefined (reading 'element')`

**Comment by rendomnet** [comment]
fixed by removing all 'migration build' changes

**Comment by duoluodexiaoxiaoyuan** [comment]
> fixed by removing all 'migration build' changes
I don't understand how to fix it. Can you explain it in detail?
