### ISSUE TITLE
Chosen item lost reactive data that's set after drag start when moved to other list.

### ISSUE THREAD

**Issue by ga676005** [SortableJS/vue.draggable.next#116]
I have a draggable list and each list item has an input checkbox. If I drag a item that is not currently checked, I want to make it the only item checked in the list. 

I run into an issue that when the chosen item is moved to different list, the chosen item will lost the latest reactive data and go back to the previous states, and when I keep dragging the chosen item and move it back to its original list, the reactive data will update to the latest snapshot. This only happens on the chosen item. And it doesn't trigger any life cycle hook and watchers.

This is how I update check list after drag start so the checkbox of the chosen item will be checked, and the checkbox of the other items will be unchecked. 
```js
const onDragStart = () => {
  referenceStore.selectedReferencesIdList = [ draggedTargetId ]
}
```

I inspect this issue with devtools and I've found that when item is dragged to other list, even with the option pull set to 'clone' like `:group="{ name: '...', pull: 'clone' }"`, the item will still be removed from the DOM and replaced by an element that was cloned right before drag start.
So I think If I can prevent the item from being removed from the DOM. This issue could be solved. 
Is there an option for this purpose?

**Comment by pedrinhoas7** [comment]
:group="{ name: '...', put: true  }"
