### ISSUE TITLE
Breaking changes

### ISSUE THREAD

**Issue by garyzoar** [SortableJS/vue.draggable.next#12]
I would like to use a nested tree and make the items draggable like in Vue 2 version.

I have tried your migration tips but it seems that the draggable component takes over the v-for and emits an element?

If so then this completely breaks code like this:

Vue 2:
```
      <draggable v-model="data">
        <el-tree :data="data"></el-tree>
      </draggable>
```

Vue 3:
```
      <draggable v-model="data" item-key="id">
        <template #item="{element, index}">
          <el-tree :data="element"></el-tree>
        </template>
      </draggable>
```

As the tree is no longer one tree but instead is multiple trees. If this is the case then I a lot of us will have to stay on vue 2...

Thanks for any response.

Gary

**Comment by David-Desmaisons** [comment]
What is the el-tree implementation?

**Comment by garyzoar** [comment]
Hi, its'

https://element-plus.org/#/en-US/component/installation

Probably the best vue 3 components in the world. I can let you have a go on what I have done with them on my CMS if like.

It enables me to drag and drop tree information for URL's menu dropdowns and the like.

I am very happy to spend as much time as you like helping with this problem as I was using many other components in a similary way but they are all broken now.

Thanks

Gary

**Comment by David-Desmaisons** [comment]
The think is with code such as this:
```
<!-- vue 2 only -->
 <draggable v-model="data">
        <el-tree :data="data"></el-tree>
</draggable>
```

There are absolutely no guarantee that the el-tree component will render one node by  element as it should in order to make it works. This is the reason that motivate the API change.

For a working example of a nested dragabble example check:
https://sortablejs.github.io/vue.draggable.next/#/nested-example

> As the tree is no longer one tree but instead is multiple trees. If this is the case then I a lot of us will have to stay on vue 2...

I am not sure of this since this example is really an edge case and in most cases the tag props allows to reuse third party components.

NB: by the way the el component you are looking at seems to have a draggable props...

**Comment by garyzoar** [comment]
The el-tree was an example of real world use for me.

How about the other problem where I have written my own component that is nested (recursive) and want to use in inside your draggable component? It will make multiple copies of the nested component and thus is unusable.

I understand vue 3 has made a lot of breaking changes but your solution is not usable anymore to anyone other than just making divs draggable.

And yes el elements does have draggable props but is not where near as flexible and useable as your original solution.

**Comment by David-Desmaisons** [comment]
Well again, you can use nested structure with the new API:
```html
<template>
  <draggable
    class="dragArea"
    tag="ul"
    :list="tasks"
    :group="{ name: 'g1' }"
    item-key="name"
  >
    <template #item="{ element }">
      <li>
        <p>{{ element.name }}</p>
        <nested-draggable :tasks="element.tasks" />
      </li>
    </template>
  </draggable>
</template>
```

Complete example here: https://sortablejs.github.io/vue.draggable.next/#/nested-example

**Comment by garyzoar** [comment]
That creates multiple items at root. Completely useless. Thanks for nothing. You've ruined a brilliant component.

**Comment by David-Desmaisons** [comment]
> That creates multiple items at root.
That´s totally wrong. 
That said given the agressivity of your last answer I will not take any extra time arguing with you.
