### ISSUE TITLE
Horizontally draggable quasar q-cards

### ISSUE THREAD

**Issue by derekneely** [SortableJS/vue.draggable.next#172]
I've seen a few 'solutions' online about this but to no avail for us. We're working with the quasar framework and trying to setup a horizontally wrapped set of <q-card> that are are draggable (for re-ordering). Below is the basic stub of the code we're working with to get this going. However, we're not able to get the cards to layout horizontally everything is stacked in a list. What are we doing wrong?

```
<template>
<div class="q-pa-md row items-start q-gutter-md">
    <draggable
      v-model="items"
      group="items"
      direction="horizontal"
      item-key="id"
      @start="drag = true"
      @end="drag = false"
    >
      <template #item="{ element }">
        <q-card class="card">
          <q-img
            src="~assets/temp/bb-auto.png"
            :alt="`Image ${element.name}`"
          >
            <div class="absolute-bottom text-subtitle2 text-center">
              Image {{ element.name }}
            </div>
          </q-img>
        </q-card>
      </template>
    </draggable>
</div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import draggable from 'vuedraggable';

const drag = ref(false);

const items = ref([
  { name: 'item1' },
  { name: 'item2' },
  { name: 'item3' },
  { name: 'item4' },
  { name: 'item5' },
]);
</script>

<style scoped>
.card {
  max-height: 200px;
  max-width: 200px;
  display: flex;
}
</style>
```

**Comment by cschra** [comment]
might be unrelated, but your item-key is `id` which is not part of your items object ... maybe change it to `item-key="name"` 
~~Other than that horizontal is the standard if you don't provide the prop, so maybe you want `vertical`?~~
 _(edit: as you have flex col I assume you want horizontal)_ 
The Sortable doc states that it detects it automatically, so maybe try to not specify it at all.

If possible provide a jsfiddle or some kind of sandbox example to make sure it is not caused by your setup

**Comment by derekneely** [comment]
Thanks for the response. It turns out my overall layout was wrong in and of itself. I got that sorted and was then able to back that into the layout I needed. Below is the working code. I needed to treat the <draggable> container as if it was my row.

```
<template>
  <draggable
    v-model="items"
    group="items"
    class="q-pa-md row items-start q-gutter-md"
    direction="horizontal"
    item-key="name"
    @start="drag = true"
    @end="drag = false"
  >
    <template #item="{ element }">
      <q-card class="card">
        <q-img src="~assets/temp/bb-auto.png" :alt="`Image ${element.name}`">
          <div class="absolute-bottom text-subtitle2 text-center">
            Image {{ element.name }}
          </div>
        </q-img>
      </q-card>
    </template>
  </draggable>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import draggable from 'vuedraggable';

const drag = ref(false);

const items = ref([
  { name: 'item1' },
  { name: 'item2' },
  { name: 'item3' },
  { name: 'item4' },
  { name: 'item5' },
]);
</script>

<style scoped>
.card {
  width: 100%;
  max-height: 200px;
  max-width: 200px;
  display: flex;
}
</style>
```

**Comment by wingzhingling** [comment]
If this is a quasar-style component,there should be a ‘content-class’ prop.
