### ISSUE TITLE
vue-draggable-next does not work for primitive values in :list prop

### ISSUE THREAD

**Issue by Kasheftin** [SortableJS/vue.draggable.next#18]
First check https://github.com/SortableJS/Vue.Draggable/blob/master/CONTRIBUTING.md

### Jsfiddle link

Repro:
https://kasheftin.github.io/vue-draggable-next-issue/

Source code:
https://github.com/Kasheftin/vue-draggable-next-issue

### Step by step scenario

First list: try to move 0-th item to 1-th position. It fails.
Second list: try to do that same. It works. 

![vue-sortable-next-issue](https://user-images.githubusercontent.com/379267/108621293-85675900-743a-11eb-9ac8-3d9f3a594c42.gif)

**Comment by alnumac** [comment]
As a workaround, I provided a function that bimply returned an the element to itemKey. Dunno if I'm going to get any issue down the line, but it seems to work great for now.
`:itemKey="(element) => element"`

**Comment by David-Desmaisons** [comment]
@Kasheftin, @alnumac  is rigth you should provide a correct value for itemkey:
`:itemKey="(element) => element"` wil work.
In your example by default itemKey will use the attribute id of a number which is undefined. All elements having the same undefined key, drag is not possible.

**Comment by goforu** [comment]
> As a workaround, I provided a function that simply returned an the element to itemKey. Dunno if I'm going to get any issue down the line, but it seems to work great for now.
> `:itemKey="(element) => element"`

works for me
