### ISSUE TITLE
Duplicated Children in Nested Draggable

### ISSUE THREAD

**Issue by ed-iv** [SortableJS/vue.draggable.next#19]
I'm having another issue with nested draggables in what I think is a fairly common use case and am wondering if anyone has some pointers. I need to create a nested list where child elements can be moved between parents. 

So to take a todo list for example, the parent might be a 'Task' that is comprised of multiple 'Todo' children. I need to be able to move a 'Todo' from one 'Task' to another.

The issue I've run into is that after moving the children to another parent moving the (now empty) causes duplicates of its children to suddenly re-appear. Trying to resolve this using shared state (vuex) but I'm at the point now where I've got to manually adjust the underlying data structure when a drag event ends.

Any ideas? I'm happy to provide more info it needed.

**Comment by MaxLeiter** [comment]
hey @ed-iv I'm running into the same problem and I'm wondering why this was closed. Were you able to solve it?
