### ISSUE TITLE
Drag & Drop stopped working in Chrome 109

### ISSUE THREAD

**Issue by singerla** [SortableJS/vue.draggable.next#191]
I was using this library for a long time now, suddenly it stopped working (now using latest Chrome 109.0.5396.0 on Windows).

Chrome 106.0.5249.119 is still working.
Firefox 106.0.2 is still working.

Try this with several browsers:
https://sortablejs.github.io/vue.draggable.next/#/simple

Unfortunately, there is no related message in console. It just stopped working silently.

As it seems as if this project is no longer maintained, I was just wondering if anybody else encountered this issue and might provide any help.

**Comment by singerla** [comment]
This also affects Edge 107.0.1418.26.

Drag & Drop seems to work *once* on latest Chrome/Edge if you do some heavy random clicking.

**Comment by singerla** [comment]
It seems as if the underlying component is affected by this:
https://sortablejs.github.io/Sortable/

**Comment by lianee** [comment]
Latest stable release of Chrome is 107.0.5304.87/88 ([27 October 2022](https://en.wikipedia.org/wiki/Google_Chrome)) and D&D works for me.
Firefox latest 106.0.3 works
Edge 107.0.1418.26 works also here
Checked on the demo page & in my program

**Comment by singerla** [comment]
Thanks a lot for testing. I could figure out why this was happening: I'm running windows on a virtual machine and mouse capturing was not working properly.

Really strange, because no other windows functionality was affected by this, just drag and drop inside edge & chrome...

VirtualBox Version 6.1.40
Guest: Windows 10
Host: Ubuntu 22.04.1
