### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by Macartini** [SortableJS/vue.draggable.next#22]
Hi guys!

Vue devtools shows me correct data in props but I can't get title, it fails with 'Cannot read property title of undefined'. Any help!

![Screenshot_28](https://user-images.githubusercontent.com/77324079/110221110-f5fa8500-7ed2-11eb-90ee-16d899b9733c.png)

**Comment by Eworm** [comment]
Same problem here:

<img width="2184" alt="Schermafbeelding 2021-03-10 om 14 45 23" src="https://user-images.githubusercontent.com/511488/110638807-46156800-81af-11eb-8d4d-9b6e079340bc.png">

**Comment by Eworm** [comment]
What happens if you rename 'slide' to something else?

**Comment by Macartini** [comment]
It's ok with {element}, I fixed it yesterday, but I think this is weird decision from the developer or at least must be documented  :)

**Comment by Eworm** [comment]
Yes!
