### ISSUE TITLE
[feat] Add typed custom event for @start and @end events. (TypeScript Support)

### ISSUE THREAD

**Issue by deathlynocturnal** [SortableJS/vue.draggable.next#225]
Hello,

Not a bug, but would be awesome if you could offer a type specific for the CustomEvent (TypeScript) for the @start and @end events that have a custom event, would be useful to have that typed, so we can pass the event around if necessary.

Thanks in advance.

**Comment by Alfred-Skyblue** [comment]
[vue-draggable-plus](https://github.com/Alfred-Skyblue/vue-draggable-plus)
