### ISSUE TITLE
TypeError: Cannot destructure property 'element' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by luisrossi** [SortableJS/vue.draggable.next#231]
I copied and pasted this exact code:
- https://github.com/SortableJS/vue.draggable.next/blob/master/example/components/two-lists.vue

But I'm getting this error:
TypeError: Cannot destructure property 'element' of 'undefined' as it is undefined.
```
"vuedraggable": "^4.0.1",
"vue": "^3.3.0",
"@vue/compat": "^3.3.0",
```

I also tried with the latest version of vuedraggable!
any suggestions on how to resolve this?

**Comment by alecgibson** [comment]
There's a very similar issue in `floating-vue`: https://github.com/Akryum/floating-vue/issues/924

I think my [comment](https://github.com/Akryum/floating-vue/issues/924#issuecomment-1658614306) from there applies here, too:

I don't think this library plays nicely with the compatibility build and the [render function break](https://v3-migration.vuejs.org/breaking-changes/render-function-api.html).

The library works for us if we disable the [`RENDER_FUNCTION`](https://v3-migration.vuejs.org/migration-build.html#compat-configuration) compatibility flag:

```js
import {configureCompat} from 'vue';

configureCompat({
  RENDER_FUNCTION: false,
});
```

**Comment by luisrossi** [comment]
To solve this problem, I had to create myself a directive that does the tooltip behavior, using floating-ui/dom.

After migrating to vue 3, he intends to remove this created directive and use the one from the component.

**Comment by davidphamntq** [comment]
https://github.com/SortableJS/vue.draggable.next/issues/122#issuecomment-1209914102
@luisrossi this issue has been already answer here

**Comment by luisrossi** [comment]
Unfortunately it didn't work for me @davidphamntq
The solution for me was to migrate to another lib, vedraggableplus 

Apparently this library has been abandoned
