### ISSUE TITLE
Can't add role or aria attributes

### ISSUE THREAD

**Issue by bbenjamin** [SortableJS/vue.draggable.next#36]
### Step by step scenario
Add `role` or any `aria-` attributes to `<draggable>` and note that they are not in the resulting HTML. Allowing these will facilitate improved accessibility for certain use cases.

###  Solution
PR, includes tests: https://github.com/SortableJS/vue.draggable.next/pull/35

**Comment by David-Desmaisons** [comment]
PR Merged.
