### ISSUE TITLE
How to disable drag ?

### ISSUE THREAD

**Issue by AngryChocobo** [SortableJS/vue.draggable.next#37]
First check https://github.com/SortableJS/Vue.Draggable/blob/master/CONTRIBUTING.md

**Comment by David-Desmaisons** [comment]
:disabled=false

**Comment by SineYing** [comment]
"vuedraggable": "^4.0.3"
:disabled=false also can drag

**Comment by eokic** [comment]
`:disabled=false` makes no sense here. It works for me with `true`.

From the [Sortable documentation](https://github.com/SortableJS/Sortable#options):
> disabled: false, // Disables the sortable **if set to true**.
