### ISSUE TITLE
the _sortable is undefined in $attrs watch handler

### ISSUE THREAD

**Issue by buqiyuan** [SortableJS/vue.draggable.next#40]
First check https://github.com/SortableJS/Vue.Draggable/blob/master/CONTRIBUTING.md

### Jsfiddle link
none
### Step by step scenario
when I use .vue template file it is normal，however when I use tsx the _sortable is undefined
### Actual Solution
![image](https://user-images.githubusercontent.com/39730999/116208737-cb5ed700-a773-11eb-818f-f3fec88ead2e.png)

**Comment by buqiyuan** [comment]
![image](https://user-images.githubusercontent.com/39730999/116209822-debe7200-a774-11eb-87ef-509ddc095db6.png)
![Uploading image.png…]()

**Comment by David-Desmaisons** [comment]
Correct by PR #17
