### ISSUE TITLE
[Vue warn]: Duplicate keys found during update

### ISSUE THREAD

**Issue by Bruce12** [SortableJS/vue.draggable.next#5]
![image](https://user-images.githubusercontent.com/13956658/103334076-2248ee00-4aab-11eb-9c1d-8415336aa8af.png)
this warning can cause each item update error，how can I avoid this warning!! "item-key" is not quite unique.
wanna be a help!! thanks

**Comment by David-Desmaisons** [comment]
Important: this a problem in the example code not in the lib itself. 

I will adapt the code to use clone hook to generate an unique id when cloning.

**Comment by Bruce12** [comment]
thanks ,it works

**Comment by Bruce12** [comment]
> Important: this a problem in the example code not in the lib itself.
> 
> I will adapt the code to use clone hook to generate an unique id when cloning.



> Important: this a problem in the example code not in the lib itself.
> 
> I will adapt the code to use clone hook to generate an unique id when cloning.

thanks!!! it works well
