### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by physihan** [SortableJS/vue.draggable.next#6]
First check https://github.com/SortableJS/Vue.Draggable/blob/master/CONTRIBUTING.md

### Step by step scenario
![image](https://user-images.githubusercontent.com/20788562/103611769-e8ba2c00-4f5d-11eb-8623-f0ef593a2452.png)

### Actual Solution
The dist lib package has unremoved console.log,while the lib override the console.log method,

**Comment by David-Desmaisons** [comment]
Hello, There is no such code:
```js
console.log('object');
```
in vue.draggable codebase.
