### ISSUE TITLE
Item key changed but component didnt rerender

### ISSUE THREAD

**Issue by gnidustotalus** [SortableJS/vue.draggable.next#69]
### Github link
https://github.com/gnidustotalus/vuedraggable-item-key-bug

### Step by step scenario
1. I have array of objects called slides. 
2. I have component Slide which is not re-rendering when item-key is changing

### Actual Solution
When key is changing component didnt re-render.

### Expected Solution
Component should re-render when key changed.

**Comment by damvik** [comment]
@David-Desmaisons Problem appears when I need validate data inside the list by vee-validate package. Can you show me an example how to use vue.draggable with vee-validate?

**Comment by damvik** [comment]
For me solution was update vee-validate to 4.5+ and using [useFieldArray](https://vee-validate.logaretm.com/v4/api/use-field-array) composable.

**Comment by kathirr007** [comment]
> For me solution was update vee-validate to 4.5+ and using [useFieldArray](https://vee-validate.logaretm.com/v4/api/use-field-array) composable.

Hi @gnidustotalus, 
Could you please provide a working example of the issue? It would be beneficial.

Thank you in Advance.
