### ISSUE TITLE
drag-class property not working

### ISSUE THREAD

**Issue by Rubanthilak** [SortableJS/vue.draggable.next#7]
```
<draggable
            :list="element.value"
            item-key="name"
            group="people"
            ghost-class="ghost"
            drag-class="drag"
          >
```
the drag-class property is not applied to the currectly dragged item.

I need to change the opacity to 1.

**Comment by prdatur** [comment]
As a work around you can use

```
chosen-class=""
ghost-class=""
```
chosen-class = both, the drop position and the one which you currently hold in your hands
ghost-class = the drop position

So if you style the drop position and then overwrite the style with the chosen-class you will have your desired style.
Anyways, the bug should be fixed or the documention must be fixed.

**Comment by Blackfaded** [comment]
Thanks for the hint!
For me the order of classes was necessary, too.

I had to style the chosen class and then had to implement the ghost class.

**Comment by adamreisnz** [comment]
This doesn't seem to work properly. Even the `chosen` class doesn't seem to be applied properly, or doesn't respect the opacity setting:

```css
.chosen {
  opacity: 1 !important;
}
.ghost {
  opacity: 0 !important;
}
```

```vue
<draggable
      v-model="items"
      item-key="id"
      :animation="200"
      :ghost-class="$style.ghost"
      :chosen-class="$style.chosen"
    >
```

This still renders the chosen item (the one you're dragging) with what seems to be a 50% opacity.

The ghost class correctly has 0 opacity though.

**Comment by adamreisnz** [comment]
Probably a browser limitation: https://stackoverflow.com/questions/9712535/html5-drag-and-drop-no-transparency

**Comment by suterma** [comment]
I can say that, e.g., `drag-class="has-text-success"` works for me, although it's about text colors, not transparency in my case. Thus, this issue should be renamed to mention transparency specifically in the title. It's closed, but I got here by a google search, and as it's worded now, it does not apply to me.

**Comment by codeparl** [comment]
please do this:
apply
:force-fallback="true" :fallback-on-body="true"
to your draggable then whenever you drag sortable will clone that element and append it to <body> with the following
classes:
sortable-fallback dragging
style the classes to achieve what you wanted, styling the dragging element.
