### ISSUE TITLE
shifting array elements in Vue 3 with composition API and @end event

### ISSUE THREAD

**Issue by jechazelle** [SortableJS/vue.draggable.next#79]
Hi,

I would like to know how can I use the @end event with composition API to shift the object in array.

Currently I have a list and when I move the first item to the second position, the first item stay first item.
When I move the first item on third position, the first item become second item.

[Demo](https://stackblitz.com/edit/vue-shifting-array-elements-wpdmq9)

I need to use the @end event to call a function.

**Comment by jessuni** [comment]
That's because you use `:list="post.comments"`. According to the docs, `list` makes use of `splice` internally, which will mutate the original array. In your case, just replacing that part with `:modelValue="post.comments"` would fix.

**Comment by jechazelle** [comment]
Thank you so much @jessuni !!
