### ISSUE TITLE
VueDraggable in nuxt error: Object(...) is not a function

### ISSUE THREAD

**Issue by ClaudiaGiv** [SortableJS/vue.draggable.next#9]
Hi,

I have a nuxt project with VueDraggable library integrated in following the steps from this issue: https://github.com/SortableJS/Vue.Draggable/issues/525
And it gives the error:
![image](https://user-images.githubusercontent.com/23199401/104621170-7bfb0c00-5698-11eb-9424-c6fd76674b15.png)
Can you help me with this problem?

Thanks

**Comment by martman85** [comment]
I seem to have the same problem.

**Comment by AndyYanAtSuzhou** [comment]
I seem to have the same problem when using Quasar

**Comment by Matb85** [comment]
+1 same problem

**Comment by David-Desmaisons** [comment]
@ClaudiaGiv could you tell me which line exactly give this error?
Could also you confirm that this error is server-side?

**Comment by David-Desmaisons** [comment]
Looking to the code it seems that the exception is raised in the mounted hook that should not be called in ssr context.

**Comment by Matb85** [comment]
Hi,
Hope you don't mind me joining in as I have the exact same issue

I have created a reproduction [repo](https://github.com/Matb85/vuedragg-nuxt) in which I use vue-draggable on the client-side add it still throws the same error, so it's probably not a ssr issue

Look at the fetch function in pages/index.vue - I put there an Object function and it works just fine

**Comment by viettranme** [comment]
Check the package.json if you're using Vue 2x or Vue 3x. `vue.draggable.next` requires Vue 3x

**Comment by ClaudiaGiv** [comment]
> @ClaudiaGiv could you tell me which line exactly give this error?
> Could also you confirm that this error is server-side?

Hi @David-Desmaisons, I found what was the problem. The version for the vue draggable library was not compatible with the version of vue in the project. (I used nuxt which still uses vue 2 and vue-draggable version for vue3 and after I change it to vue-draggable version for vue2 it worked. I am not sure if there was anything else that I modified and also helped here, but this was the main issue.)
Thanks and sorry for the late reply.

**Comment by ClaudiaGiv** [comment]
> Hi,
> Hope you don't mind me joining in as I have the exact same issue
> 
> I have created a reproduction [repo](https://github.com/Matb85/vuedragg-nuxt) in which I use vue-draggable on the client-side add it still throws the same error, so it's probably not a ssr issue
> 
> Look at the fetch function in pages/index.vue - I put there an Object function and it works just fine

@Matb85 , shouldn't you have added a plugin for vue draggable and declare it in nuxt-config?

**Comment by Matb85** [comment]
I prefer to import a component every time I need it than to set it as a global plugin. Nevertheless, if you declared vue draggable in nuxt-config and it worked, then great. I'll definitely give this approach a go.

**Comment by Matb85** [comment]
ok so I downgraded to vue-draggable for vue 2 and everything worked!
Thanks a lot.
