### ISSUE TITLE
Table CDN example dom error

### ISSUE THREAD

**Issue by hunteryun** [SortableJS/vue.draggable.next#90]
```
    <div id="App">
        <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Id</th>
                <th scope="col">Name</th>
                <th scope="col">Sport</th>
              </tr>
            </thead>
            <vuedraggable v-model="list" tag="tbody" item-key="name">
              <template #item="{ element }">
                <tr>
                  <td scope="row">{{ element.id }}</td>
                  <td>{{ element.name }}</td>
                  <td>{{ element.sport }}</td>
                </tr>
              </template>
            </vuedraggable>
        </table>
    </div>
    
      <script>
          Vue.createApp({
            components: {
                vuedraggable
            },
            data() {
            return {
                list: [
                    { id: 1, name: "Abby", sport: "basket" },
                    { id: 2, name: "Brooke", sport: "foot" },
                    { id: 3, name: "Courtenay", sport: "volley" },
                    { id: 4, name: "David", sport: "rugby" }
                ]
            };
            }
        }).mount("#App");
      </script>

```

![image](https://user-images.githubusercontent.com/22260884/138286107-ec6fb213-7da7-4579-ba17-89ad2a2c8056.png)

**Comment by kabanoki** [comment]
I am experiencing the same problem.
Is there a workaround?

**Comment by hunteryun** [comment]
@kabanoki No, I keep use old version

**Comment by kabanoki** [comment]
@hunteryun 

I've figured out how to make it work!

Change it as follows
`<vuedraggable v-model="list" tag="tbody" item-key="name">`
↓
`<tbody is="vue:vuedraggable" v-model="list" tag="tbody" item-key="name">`


Sample URL
[https://codepen.io/kabanoki/pen/zYEVwrp](https://codepen.io/kabanoki/pen/zYEVwrp)

**Comment by hunteryun** [comment]
@kabanoki WOW，you are legend !  :thumbsup:

**Comment by peterstavrou** [comment]
Has anyone got this to work using the **Simple demo**?
I tried using [kabanoki](https://github.com/kabanoki)'s code as a reference but having trouble.

**Comment by hunteryun** [comment]
what's trouble with you? show your code?

**Comment by PeterStavrou** [comment]
> what's trouble with you? show your code?
Here is my code:
https://jsfiddle.net/squidg/mev83ngo/2/

I'm getting the following in console.
```
Uncaught TypeError: Cannot read properties of undefined (reading 'type')
    at Kc (vue.global.prod.js:1:97696)
    at Kc (vue.global.prod.js:1:97732)
    at zc (vue.global.prod.js:1:97560)
    at Wc (vue.global.prod.js:1:97405)
    at zc (vue.global.prod.js:1:97552)
    at vue.global.prod.js:1:98383
    at Kc (vue.global.prod.js:1:98540)
    at Kc (vue.global.prod.js:1:97732)
    at zc (vue.global.prod.js:1:97560)
    at Wc (vue.global.prod.js:1:97405)
```

**Comment by peterstavrou** [comment]
> > what's trouble with you? show your code?
>
>  Here is my code:
>  https://jsfiddle.net/squidg/mev83ngo/3/
> 
> I'm getting the following in console.
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'type')
>     at Kc (vue.global.prod.js:1:97696)
>     at Kc (vue.global.prod.js:1:97732)
>     at zc (vue.global.prod.js:1:97560)
>     at Wc (vue.global.prod.js:1:97405)
>     at zc (vue.global.prod.js:1:97552)
>     at vue.global.prod.js:1:98383
>     at Kc (vue.global.prod.js:1:98540)
>     at Kc (vue.global.prod.js:1:97732)
>     at zc (vue.global.prod.js:1:97560)
>     at Wc (vue.global.prod.js:1:97405)
> ```

**Comment by kabanoki** [comment]
@PeterStavrou 

For now, if you just want to see it in action, take a look at the sample below.
https://jsfiddle.net/kabanoki/fszm3w47/11

Only some HTML has been changed.

**Comment by peterstavrou** [comment]
> For now, if you just want to see it in action, take a look at the sample below. https://jsfiddle.net/kabanoki/fszm3w47/11

Perfect! Thank you!

**Comment by hilmanski** [comment]
> @PeterStavrou
> 
> For now, if you just want to see it in action, take a look at the sample below. https://jsfiddle.net/kabanoki/fszm3w47/11
> 
> Only some HTML has been changed.

Appreciate your help!
