### ISSUE TITLE
Is there any way to add input fields within a draggable section?

### ISSUE THREAD

**Issue by megasanjay** [SortableJS/vue.draggable.next#96]
First, check https://github.com/SortableJS/Vue.Draggable/blob/master/CONTRIBUTING.md

Been using this to handle a set of inputs that should be draggable but I find that adding inputs and setting a v-model cause the input to lose focus after a character is typed since vue draggable refreshes the layout. This will lead to an annoying typing experience. Is there any way to set the refresh to stop while an input has focus?

**Comment by megasanjay** [comment]
Figured it out. You need to have a key in the object that is not one of the input elements. Adding an id attribute seemed to be the answer. Closing this issue.

**Comment by lucianobosco** [comment]
Hi, could you please elaborate or show some example? I'm facing the same issue when using input with v-model

**Comment by megasanjay** [comment]
> Hi, could you please elaborate or show some example? I'm facing the same issue when using input with v-model

@lucianobosco Let me know if you have any questions

I use Element Plus for my UI but I think it should still be applicable for you. I can add links to the line numbers where I use it so you can take a look:

- Template: [FigshareMetadata.vue#L156-L211](https://github.com/fairdataihub/FAIRshare/blob/main/src/views/figshare/FigshareMetadata.vue#L156-L211)
- Functions to add and delete items: [FigshareMetadata.vue#L577-L594](https://github.com/fairdataihub/FAIRshare/blob/main/src/views/figshare/FigshareMetadata.vue#L577-L594)
- Move cursor to newly added input: [FigshareMetadata.vue#L504-L512](https://github.com/fairdataihub/FAIRshare/blob/main/src/views/figshare/FigshareMetadata.vue#L504-L512)

**Comment by lucianobosco** [comment]
@megasanjay thanks! I really appreciate it. Since I'm using quasar it looks pretty similar.
I'm trying to figure out how to properly set styles to attach children. Having no padding at bottom parent element drives to a buggy behaviour.

Without paddings (dotted area) drag and drop is really annoying. Did you manage to make it work in a nice way?
https://pasteboard.co/3vRCVb9qnyIW.png

**Comment by megasanjay** [comment]
@lucianobosco Yeah. Are you using the `handle` prop? My app seems to work pretty well with it at least. I don't have any style issues with this library.
